### ISSUE TITLE
Give a reason to read one of the books ?

### ISSUE THREAD

**Issue by MaximeArnstamm** [tron1991/open-product-management#3]
There are a lot of books, unsorted, and for some i don't see the reason for their presence, like the martian.

A short sentence or a tldr; would be enough

**Comment by lgriffin** [comment]
I'd say better sub headings and groupings rather than give me a reason. Like The Martian is in with a list of other books that as a whole don't make sense but if grouped they did. Algorithms and Products Customers Love don't make sense in the context of The Martian (and I did love that book!).

**Comment by tron1991** [comment]
I agree with Igriffin, subheadings for the books will have better organization. It's on my TODO for today.

**Comment by tron1991** [comment]
Subheadings are added now. Cheers.
